version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: db-nest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3307:3306'
    volumes:
      - ./db:/var/lib/mysql
